config/routes.rb
Rails.application.routes.draw do
  
  resources :activities
  resources :companies
resources :users, :except => [:show, :destroy]

  root 'static#help'
  get 'static/help'

  match '/users',   to: 'users#index',   via: 'get'
  devise_for :users, :skip => :registrations
  
  devise_scope :user do
    get '/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch '/users' => 'devise/registrations#update'
    put '/users' => 'devise/registrations#update'
    post '/users' => 'devise/registrations#create', :as => 'user_registration'
    get "/login" => "devise/sessions#new"
    delete "/users" => "users#delete_user"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable 
  has_and_belongs_to_many :companies
  belongs_to :role
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate_user!, :authenticate_admin
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def delete_user
    @deleted_user = User.find(params[:id])
    @deleted_user.destroy
    redirect_to :action => :index
  end

  def update
    @user = User.find(params[:id])
    @user.companies =  params[:user][:companies].empty? ? [] : [Company.find(params[:user][:companies])]

    if @user.update_attributes(params.require(:user).permit(:role_id))
      flash[:success] = 'Usuário editado com sucesso'
    else
      flash[:notice] = "Não foi possível editar usuário"
    end
    redirect_to action: "index"
  end

  def authenticate_admin
    if !isAdmin?
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2><%= "Editar Perfil" %></h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@user, :html => { :method => :put,  class: 'form-horizontal'}) do |f| %>

      <%= f.label :avatar %>
      <div class="text-center">
        <%= image_tag(@user.avatar.url(:thumb), :align=> "middle")%><br>
      </div>

      <%= f.label :name %>
      <%= f.email_field :name,:readonly => true, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email,:readonly => true, class: 'form-control' %>
      
      <%= f.label "Tipo de Usuário" %>
      <%= f.collection_select :role_id, Role.order(:name),:id,:name, include_blank: true %>

      <%= f.label "Empresa" %>
      <%= f.collection_select :companies, Company.order(:fantasy_name),:id,:fantasy_name,selected: @user.companies.first.nil? ? {} : @user.companies.first.id, include_blank: true %>

      <%= f.submit "Salvar Mudanças", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<table data-toggle="table" data-search="true">
  <thead>
      <tr>
          <th>Nome</th>
          <th>Tipo</th>
          <th>Empresa</th>
          <th></th>
      </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.role.name %></td>
      <td>
        <% if user.companies.first != nil %>
          <%= user.companies.first.fantasy_name %>
        <% end %>
      </td>
      <td>
        <div class='wrapper text-center'>
          <div class="btn-group btn-group-sm">
            <% if isAdmin? %>
              <%= link_to "excluir", {:controller => :users, :action => 'delete_user', :id => user.id }, :method => :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger', role: "button" %>
              <%= link_to "editar", edit_user_path(user), class: 'btn btn-mini btn-warning', role: "button" %>
            <% end %>
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>