config/routes.rb
Rails.application.routes.draw do
  
  resources :activities
  resources :companies
resources :users, :except => [:show, :destroy]

  root 'static#help'
  get 'static/help'

  match '/users',   to: 'users#index',   via: 'get'
  devise_for :users, :skip => :registrations
  
  devise_scope :user do
    get '/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch '/users' => 'devise/registrations#update'
    put '/users' => 'devise/registrations#update'
    post '/users' => 'devise/registrations#create', :as => 'user_registration'
    get "/login" => "devise/sessions#new"
    delete "/users" => "users#delete_user"
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :company_phase, :foreign_key => 'phase_id'
  belongs_to :company_type, :foreign_key => 'type_id'
  has_many :activities
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
	has_many :companies, :foreign_key => 'type_id'
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include ApplicationHelper
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :authenticate_admin, only: [:create, :new, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|

      @companyUsers = []
      if params[:company][:users] != nil
        for userId in params[:company][:users]
          if userId != ""
            user = User.find(userId)
            if user.companies.empty?
              @companyUsers.push(User.find(userId))
            end
          end
        end
      end
      @company.users = @companyUsers

      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|

      @companyUsers = []
      if params[:company][:users] != nil
        for userId in params[:company][:users]
          if userId != ""
            user = User.find(userId)
            if user.companies.empty?
              @companyUsers.push(User.find(userId))
            end
          end
        end
      end
      @company.users = @companyUsers
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company

      @company = Company.find(params[:id])

      @activitiesCompleted = 0
      @activitiesPending = 0

      for activity in @company.activities
        if (!activity.result_file_size.nil?)
          @activitiesCompleted += 1
        else
          @activitiesPending += 1
        end
      end

      @users = []
      User.order(:id)
      for user in User.order(:id)
        if user.companies.empty? || user.companies.first.id == @company.id
          @users.push(user)
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:logo, :fantasy_name, :company_name, :cnpj, :description, :cep, :street, :area, :complement, :city, :state, :phone, :email, :facebook, :twitter, :type_id, :phase_id)
    end

    def authenticate_admin
      if !isAdmin?
        redirect_to root_path
      end
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :logo, :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.file_field :logo, :class=>"form-control" %>
          </div>
        </div>
        <hr class="margin-75">
        <div class="form-group">
          <%= f.label 'Nome Fantasia', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :fantasy_name, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Razão Social', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :company_name, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'CNPJ', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :cnpj, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Descrição', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_area :description, :class=>"form-control", cols: "30", rows: "5" %>
          </div>
        </div>
        <hr size="10">
        <div class="form-group">
          <%= f.label 'CEP', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :cep, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Logradouro', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :street, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Comp.', :title=>"Complemento", :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :complement, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Bairro', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :area, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Cidade', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :city, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Estado', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :state, :class=>"form-control" %>
          </div>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <label class="col-xs-2 control-label">Tipo</label>
          <div class="col-xs-10">
            <% if isAdmin? %>
              <%= f.collection_select :type_id, CompanyType.order(:name),:id,:name, include_blank: false %>
            <% else %>
              <%= f.label @company.company_type.name %>
            <% end %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-xs-2 control-label">Fase</label>
          <div class="col-xs-10">
            <% if isAdmin? %>
              <%= f.collection_select :phase_id, CompanyPhase.order(:name),:id,:name, include_blank: false %>
            <% else %>
              <%= f.label @company.company_phase.name %>
            <% end %>
          </div>
        </div>
        <hr size="10">  
        <div class="form-group">
          <%= f.label 'Telefone', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :phone, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Email', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :email, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Facebook', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :facebook, :class=>"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label 'Twitter', :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :twitter, :class=>"form-control" %>
          </div>
        </div>
        <hr class="margin-300">
        <div class="form-group">
          <%= f.label 'Usuários envolvidos'%>
          
          <div>
            <%= f.collection_select(:users, @users, :id, :name, {:selected => @company.users.map(&:id)}, {:multiple => true, id: "my-select", class: "searchable"}) %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'Voltar', companies_path, method: :get,class: 'btn btn-default', role: "button" %>
  <button type="submit" class="btn btn-primary">Salvar mudanças</button>
<% end %>

<script type="text/javascript">
  $('#my-select').multiSelect({
    selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Usuários'>",
    selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Usuários da Empresa'>",
    afterInit: function(ms){
      var that = this,
          $selectableSearch = that.$selectableUl.prev(),
          $selectionSearch = that.$selectionUl.prev(),
          selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
          selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

      that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
      .on('keydown', function(e){
        if (e.which === 40){
          that.$selectableUl.focus();
          return false;
        }
      });

      that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
      .on('keydown', function(e){
        if (e.which == 40){
          that.$selectionUl.focus();
          return false;
        }
      });
    },
    afterSelect: function(){
      this.qs1.cache();
      this.qs2.cache();
    },
    afterDeselect: function(){
      this.qs1.cache();
      this.qs2.cache();
    }
  });

</script>

app/views/companies/edit.html.erb
<h2>Empresa</h2>

<%= render 'form' %>

app/views/companies/index.html.erb
<% if isAdmin? %>
  <%= link_to 'Criar', new_company_path, method: :get,class: 'btn btn-default create-btn', role: "button" %>
<% end %>
<table data-toggle="table" data-search="true">
  <thead>
      <tr>
          <th></th>
          <th>Empresa</th>
          <th></th>
      </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td>
      <% @late = false %>
        <% company.activities.each do |activity| %>
          <% if Date.today > activity.end_at && activity.result_file_size.nil? %>
            <% @late = true %>
          <% end %>
        <% end %>
        <% if @late %>
          <img style="width: 30px" src="/late_icon.png">
        <% else %>
          <img style="width: 30px" src="/notlate_icon.png">
        <% end %>
      </td>
      <td><%= company.fantasy_name %></td>
      <td>
        <div class='wrapper text-center'>
          <div class="btn-group btn-group-sm">
            <%= link_to 'Show', company, method: :get,  class: 'btn btn-mini btn-success', role: "button" %>
            <%= link_to 'Edit', edit_company_path(company), class: 'btn btn-mini btn-warning', role: "button" %>
            <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger', role: "button" %>
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h2>Nova Empresa</h2>

<%= render 'form' %>

app/views/companies/show.html.erb
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <h2>Empresa</h2>
  <div class="container ">

    <div class="row">
      <div class="text-center">
        <%= image_tag(@company.logo.url(:thumb), :align=> "left")%>
      </div>
    </div>
     <div class="row">
      <div class="col-xs-6">
        <hr size="10">
        <p>
          <strong><%= @company.fantasy_name %></strong>
        </p>
        <p>
          <%= @company.company_name %>
        </p>
        <p>
          <%= @company.cnpj %>
        </p>
        <div class="textcontainer scrollable">
          <p>
            <%= @company.description %>
          </p>
        </div>

        <hr size="10">

        <p>
          <%= @company.street %>
        </p>

        <p>
          <%= @company.area %>
        </p>

        <p>
          <%= @company.city %>
        </p>

        <p>
          <%= @company.state %>
        </p>

        <hr size="10" class="margin-100">

        <p>
          <strong>Desempenho</strong>
        </p>

        <div class="bodycontainer scrollable">
          <%= pie_chart(
          {"Atividades Terminadas" => @activitiesCompleted, "Atividades Pendentes" => @activitiesPending},
          height: "105px"
          ) %>
        </div>

      </div>
      <div class="col-xs-6">
        <hr size="10">
        <p>
          <%= @company.phone %>
        </p>

        <p>
          <%= @company.email %>
        </p>

        <p>
          <%= @company.facebook %>
        </p>

        <p>
          <%= @company.twitter %>
        </p>

        <hr size="10"  class="margin-48">

        <p>
          <strong>Usuários envolvidos</strong>
        </p>

        <div class="bodycontainer scrollable">
          <table data-toggle="table" data-search="false" class="table-condensed table-striped" >
            <thead>
              <tr>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @company.users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.role.name %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <hr size="10"  class="">

        <p>
          <strong>Atividades</strong>
        </p>

        <div class="bodycontainer scrollable">
          <table data-toggle="table" data-search="false" class="table-condensed table-striped" >
            <thead>
              <tr>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @company.activities.each do |activity| %>
              <tr>
                <td><%= link_to activity.name, activity, method: :get %></td>
                <td><%= Date.strptime(activity.start_at.to_s, "%Y-%m-%d").strftime("%d/%m/%Y") %></td>
                <td>
                  <%= Date.strptime(activity.end_at.to_s, "%Y-%m-%d").strftime("%d/%m/%Y") %>
                  <% if Date.today > activity.end_at && activity.result_file_size.nil? %>
                    <font color="red"><%= "atrasado" %></font>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
</div>


<%= link_to 'Editar', edit_company_path(@company), method: :get,class: 'btn btn-primary', role: "button" %>
<%= link_to 'Voltar', companies_path, method: :get,class: 'btn btn-default', role: "button" %>