config/routes.rb
Rails.application.routes.draw do
  
  resources :activities
  resources :companies
resources :users, :except => [:show, :destroy]

  root 'static#help'
  get 'static/help'

  match '/users',   to: 'users#index',   via: 'get'
  devise_for :users, :skip => :registrations
  
  devise_scope :user do
    get '/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch '/users' => 'devise/registrations#update'
    put '/users' => 'devise/registrations#update'
    post '/users' => 'devise/registrations#create', :as => 'user_registration'
    get "/login" => "devise/sessions#new"
    delete "/users" => "users#delete_user"
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :activity_category, :foreign_key => 'category_id'
  belongs_to :company

  has_attached_file :template
  has_attached_file :result
  validates_attachment :template, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
  validates_attachment :result, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :description, :company_id, :category_id, :template, :result, :start_at, :end_at)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>

  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">

        <div class="form-group">
          <%= f.label "Nome", :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_field :name, :class=>"form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Descrição", :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <%= f.text_area :description, :class=>"form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-xs-2 control-label">Empresa</label>
          <div class="col-xs-10">
            <%= f.collection_select :company_id, Company.order(:fantasy_name),:id,:fantasy_name, include_blank: true %>
          </div>
        </div>

         <div class="form-group">
          <label class="col-xs-2 control-label">Categoria</label>
          <div class="col-xs-10">
            <%= f.collection_select :category_id, ActivityCategory.order(:name),:id,:name, include_blank: true %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Início", :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <div class='input-group date' id='datetimepicker1'>
              <%= f.text_field :start_at, :class=>"form-control", :value => @activity.start_at.try(:strftime, "%d/%m/%Y")  %>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Fim", :class=>"col-xs-2 control-label" %>
          <div class="col-xs-10">
            <div class='input-group date' id='datetimepicker2'>
              <%= f.text_field :end_at, :class=>"form-control", :value => @activity.end_at.try(:strftime, "%d/%m/%Y")   %>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="col-xs-2 control-label">Template</label>
          <div class="col-xs-10">
            <%= f.file_field :template %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-xs-2 control-label">Resultado</label>
          <div class="col-xs-10">
            <%= f.file_field :result %>
          </div>
        </div>

      </div>
    </div>
  </div>
  <script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker({
            format: 'DD-MM-YYYY',
        });
        $('#datetimepicker2').datetimepicker({
            format: 'DD-MM-YYYY'
        });
    });
  </script>
  <%= link_to 'Voltar', activities_path, method: :get,class: 'btn btn-default', role: "button" %>
  <button type="submit" class="btn btn-primary">Salvar mudanças</button>
<% end %>

app/views/activities/edit.html.erb
<h2>Editando Atividade</h2>

<%= render 'form' %>

app/views/activities/index.html.erb
<%= link_to 'Criar', new_activity_path, method: :get,class: 'btn btn-default create-btn', role: "button" %>
<table data-toggle="table" data-search="true">
  <thead>
      <tr>
          <th>Atividade</th>
          <th>Empresa</th>
          <th>Início</th>
          <th>Fim</th>
          <th></th>
      </tr>
  </thead>
  <tbody>
    <% @activities.each do |activity| %>
    <tr>
      <td><%= activity.name %></td>
      <td><%= link_to activity.company.fantasy_name, activity.company, method: :get%></td>
      <td><%= Date.strptime(activity.start_at.to_s, "%Y-%m-%d").strftime("%d/%m/%Y") %></td>
      <td>
        <%= Date.strptime(activity.end_at.to_s, "%Y-%m-%d").strftime("%d/%m/%Y") %>
        <% if Date.today > activity.end_at && activity.result_file_size.nil? %>
          <font color="red"><%= "atrasado" %></font>
        <% end %>
      </td>
      <td>
        <div class='wrapper text-center'>
          <div class="btn-group btn-group-sm">
            <%= link_to 'Show', activity, class: 'btn btn-mini btn-success', role: "button" %>
            <%= link_to 'Edit', edit_activity_path(activity), class: 'btn btn-mini btn-warning', role: "button" %>
            <%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger', role: "button" %>
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/activities/new.html.erb
<h2>Nova Atividade</h2>

<%= render 'form' %>

app/views/activities/show.html.erb
<h2>Atividade</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      <label class="col-xs-2 control-label">Nome</label>
      <div class="col-xs-10">
        <label style="font-weight:normal"><%= @activity.name %></label>
      </div>
    </div>

    <div class="form-group">
      <label class="col-xs-2 control-label">Descrição</label>
      <div class="col-xs-10">
        <textarea style="font-weight:normal" readonly="true"><%= @activity.description %></textarea>
      </div>
    </div>


    <div class="form-group">
      <label class="col-xs-2 control-label">Empresa</label>
      <div class="col-xs-10">
        <label style="font-weight:normal" :class="form-control"> <%= @activity.company.fantasy_name %></label>
      </div>
    </div>

    <div class="form-group">
      <label class="col-xs-2 control-label">Categoria</label>
      <div class="col-xs-10">
        <label style="font-weight:normal" :class="form-control">
        <% if !@activity.activity_category.nil? %>
          <%= @activity.activity_category.name %>
        <% else %>
          <%= "Nenhuma categoria associada a essa atividade" %>
        <% end %>
        </label>
      </div>
    </div>

    <div class="form-group">
      <label class="col-xs-2 control-label">Início</label>
      <div class="col-xs-10">
        <label style="font-weight:normal" :class="form-control"> <%= Date.strptime(@activity.start_at.to_s, "%Y-%m-%d").strftime("%d/%m/%Y") %></label>
      </div>
    </div>

    <div class="form-group">
      <label class="col-xs-2 control-label">Fim</label>
      <div class="col-xs-10">
        <label style="font-weight:normal" :class="form-control"> <%= Date.strptime(@activity.start_at.to_s, "%Y-%m-%d").strftime("%d/%m/%Y") %></label>
      </div>
    </div>

    <div class="form-group">
      <label class="col-xs-2 control-label">Template</label>
      <div class="col-xs-10">
        <% if !@activity.template_file_name.nil? %>
          <%= link_to @activity.template_file_name + " (Clique para baixar)", @activity.template.url(:original, false), :format => 'pdf' %>
        <% else %>
          <%= "Nenhum template foi adicionado a esta atividade" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Editar', edit_activity_path(@activity), method: :get,class: 'btn btn-primary', role: "button" %>
<%= link_to 'Voltar', activities_path, method: :get,class: 'btn btn-default', role: "button" %>