config/routes.rb
Rails.application.routes.draw do
  
  resources :activities
  resources :companies
resources :users, :except => [:show, :destroy]

  root 'static#help'
  get 'static/help'

  match '/users',   to: 'users#index',   via: 'get'
  devise_for :users, :skip => :registrations
  
  devise_scope :user do
    get '/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch '/users' => 'devise/registrations#update'
    put '/users' => 'devise/registrations#update'
    post '/users' => 'devise/registrations#create', :as => 'user_registration'
    get "/login" => "devise/sessions#new"
    delete "/users" => "users#delete_user"
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Edetec", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Timeline", root_path %></li>
        <li><%= link_to "Atividades", activities_path, method: :get %></li>
        <li><%= link_to "Empresas", companies_path, method: :get %></li>
        <% if isAdmin? %>
          <li><%= link_to "Usuários", users_path, method: :get %></li>
        <% end %>
        <% if user_signed_in?  %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Conta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", '#' %></li>
        <% end %>
        <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EdetecWeb</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <% if user_signed_in?  %>
      <%= render 'layouts/header' %>
    <% end %>
    <div class="container">
      <%= flash_messages %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>